language: python
cache: pip

python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

sudo: false

env:
    - DJANGO=2.0
    - DJANGO=3.0
    - DJANGO=3.1

matrix:
    fast_finish: true

install:
    - pip install tox tox-travis

script:
    - tox
